/**
 * Core TypeScript interfaces for the RAKSHA Silent Activation (SOSSession)
 * system.
 *
 * ─── TIMESTAMP RULE ──────────────────────────────────────────────────────────
 * All Date fields in this file use JavaScript's native Date class.
 * Firestore Timestamp is NEVER used in any SOSSession-related code.
 * Violations cause deserialization failures at runtime.
 *
 * Use assertDate() / assertDateOrNull() from utils/assertDate.ts to guard
 * every timestamp field when reading from Firestore.
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * Design: RAKSHA Technical Design — Discreet Silent Activation §Data Model
 * Requirements: design.md §Data Model, tasks.md Task 1
 */

// ---------------------------------------------------------------------------
// Trigger types
// ---------------------------------------------------------------------------

/**
 * The four permitted gesture trigger types.
 *
 * - power_button : Android-TWA only (native RakshaBridge; iOS scoped out of
 *                  Phase 1 — see design.md §Decision 1).
 * - earbud       : Media Session API 'previoustrack' (triple-click).
 * - duress_phrase: On-device sherpa-onnx keyword spotter match.
 * - duress_pin   : bcrypt cost=10 duress-PIN match.
 *                  Minimum PIN length: 6 digits (raised from 4 after the
 *                  brute-force analysis in design.md §PIN Brute-Force Analysis).
 */
export type TriggerType =
  | "power_button"
  | "earbud"
  | "duress_phrase"
  | "duress_pin";

/** All four permitted TriggerType values as a const array for runtime guards. */
export const TRIGGER_TYPES: ReadonlyArray<TriggerType> = [
  "power_button",
  "earbud",
  "duress_phrase",
  "duress_pin",
] as const;

// ---------------------------------------------------------------------------
// Session status
// ---------------------------------------------------------------------------

/**
 * Three valid status values for a SOSSession document.
 *
 * State machine (all transitions performed exclusively by Cloud Functions):
 *   — → countdown   : createSOSSession (initial creation)
 *   countdown → active    : activateSOSSession Cloud Tasks handler (10 s elapsed)
 *   countdown → cancelled : cancelSOSSession callable
 *   active    → (no exit) : terminal
 *   cancelled → (no exit) : terminal
 *
 * 'enqueue_failed' is an additional terminal status written when
 * createSOSSession cannot enqueue the activation task (design.md Task 2.8).
 */
export type SOSSessionStatus =
  | "countdown"
  | "active"
  | "cancelled"
  | "enqueue_failed";

/**
 * Runtime-checkable const object for SOSSessionStatus guard.
 *
 * Usage:
 *   if (SOS_SESSION_STATUS[value as SOSSessionStatus]) { ... }
 */
export const SOS_SESSION_STATUS: Readonly<Record<SOSSessionStatus, true>> = {
  countdown: true,
  active: true,
  cancelled: true,
  enqueue_failed: true,
} as const;

// ---------------------------------------------------------------------------
// Location
// ---------------------------------------------------------------------------

/**
 * One-way-hashed GPS coordinates.
 *
 * Raw coordinates are NEVER stored.
 * Each value is a SHA-256 hex digest of the coordinate truncated to
 * 3 decimal places (≈ 110 m grid square).
 */
export interface HashedLocation {
  /** SHA-256 of latitude truncated to 3 decimal places. */
  latHash: string;
  /** SHA-256 of longitude truncated to 3 decimal places. */
  lngHash: string;
}

// ---------------------------------------------------------------------------
// SOSSession document  (/sosSessions/{sessionId})
// ---------------------------------------------------------------------------

/**
 * Canonical shape of a Firestore document at /sosSessions/{sessionId}.
 *
 * WRITE RULES:
 *   - createSOSSession CF creates the document; client NEVER writes directly.
 *   - activateSOSSession CF writes {status, activatedAt, updatedAt}.
 *   - cancelSOSSession CF writes {status, cancelledAt, updatedAt}.
 *   - All writes use Firebase Admin SDK (bypasses Firestore security rules).
 *
 * TIMESTAMP RULE: every Date field below carries the annotation
 *   // NEVER Firestore Timestamp
 * Violations cause silent runtime failures — assertDate() will throw.
 */
export interface SOSSession {
  /** Firestore document ID (UUID generated by createSOSSession). */
  sessionId: string;

  /** Firebase Auth UID of the triggering user. */
  userId: string;

  /** The gesture that initiated this SOS session. */
  triggerType: TriggerType;

  /**
   * Client wall-clock time at the moment the gesture was detected.
   * Sourced from the client payload (triggeredAt field), NOT from server
   * receive time.  The server validates the window (≤72 h past, never
   * future) but never substitutes its own timestamp.
   *
   * NEVER Firestore Timestamp.
   */
  triggeredAt: Date;

  /**
   * Server wall-clock time when createSOSSession executed.
   *
   * NEVER Firestore Timestamp.
   */
  createdAt: Date;

  /** Current document status. Only Cloud Functions write this field. */
  status: SOSSessionStatus;

  /**
   * Server time when countdown → cancelled transition committed.
   * Null until cancelSOSSession executes.
   *
   * NEVER Firestore Timestamp.
   */
  cancelledAt: Date | null;

  /**
   * Server time when countdown → active transition committed.
   * Null until activateSOSSession executes.
   *
   * NEVER Firestore Timestamp.
   */
  activatedAt: Date | null;

  /**
   * One-way hashed GPS coordinates at trigger time.
   * Null if location was unavailable at trigger time.
   */
  location: HashedLocation | null;

  /** Opaque device info string (OS, browser UA, TWA version, etc.). */
  deviceInfo: string;

  /**
   * Rounded minutes between triggeredAt and syncedAt.
   * Null for real-time triggers (syncedAt ≈ triggeredAt).
   * Non-null when the payload was queued offline and flushed later.
   */
  syncDelayMinutes: number | null;

  /**
   * True when syncDelayMinutes ≥ 60 (payload was queued for ≥ 1 hour).
   * Used to flag late-sync sessions in the audit log and downstream features.
   */
  lateSyncFlag: boolean;
}

// ---------------------------------------------------------------------------
// createSOSSession callable interface
// ---------------------------------------------------------------------------

/**
 * Payload sent by the client to the createSOSSession HTTPS callable.
 *
 * TIMESTAMP ENCODING: both timestamps are ISO 8601 strings on the wire.
 * The server parses them to Date objects and validates the window.
 *
 * Design: §Interface Boundary
 */
export interface CreateSOSSessionPayload {
  /** Gesture type that fired the trigger. */
  triggerType: TriggerType;

  /**
   * Client wall-clock at the moment the gesture was detected.
   * ISO 8601 string.  Validated server-side: must be ≤72 h in the past
   * and must not be in the future (±5 s tolerance).
   */
  triggeredAt: string;

  /**
   * Client wall-clock at the moment the HTTPS call is made.
   * ISO 8601 string.  For real-time triggers, syncedAt ≈ triggeredAt.
   * For offline-queued payloads the gap may be hours.
   */
  syncedAt: string;

  /**
   * Hashed location at trigger time, or null if unavailable.
   */
  location: HashedLocation | null;

  /** Opaque device info string. */
  deviceInfo: string;
}

// ---------------------------------------------------------------------------
// createSOSSession callable response
// ---------------------------------------------------------------------------

/**
 * Response from the createSOSSession HTTPS callable.
 *
 * Design: §Interface Boundary
 */
export interface CreateSOSSessionResponse {
  /** Firestore document ID of the created (or existing) SOSSession. */
  sessionId: string;

  /**
   * Status at return time.
   * 'active' when the trigger was late-synced and the 10 s countdown had
   * already elapsed by the time createSOSSession ran.
   * 'countdown' for real-time triggers.
   */
  status: "countdown" | "active";

  /**
   * True when the request was a duplicate (same userId + triggeredAt within
   * ±5 s tolerance) and the existing document was returned unchanged.
   */
  alreadyExists: boolean;
}
