/**
 * KMSMock — test/emulator substitute for the real Cloud KMS client.
 *
 * Used automatically when:
 *   - process.env.FUNCTIONS_EMULATOR === 'true'  (Firebase Emulator Suite)
 *   - process.env.NODE_ENV === 'test'             (vitest / jest)
 *
 * STATELESS DESIGN: The mock does NOT use an in-memory store. Instead,
 * generateDataEncryptionKey base64-encodes the plaintext DEK as the
 * "encrypted" form, prefixed with a sentinel so decryptDataEncryptionKey
 * can identify and reverse it without any shared state.
 *
 * This is safe for emulator/test use only — in production, the real
 * CloudKMSClient uses GCP KMS which provides actual encryption.
 *
 * The sentinel prefix "MOCK:" lets decryptDataEncryptionKey distinguish
 * mock-encrypted DEKs from real ones and fail fast if a real encrypted
 * DEK is accidentally passed to the mock.
 *
 * Requirements: 4.3, 4.4
 * Design: §KMS Encryption Interface — Mock Implementation
 */
import crypto from "crypto";
import type { KMSClient } from "./kms.interface.js";

const MOCK_PREFIX = "MOCK:";

export class KMSMock implements KMSClient {
  async generateDataEncryptionKey(_keyRingRef: string): Promise<{
    encryptedDEK: string;
    plaintextDEK: Buffer;
    iv: Buffer;
  }> {
    const plaintextDEK = crypto.randomBytes(32); // 256-bit AES key
    const iv = crypto.randomBytes(12); // 96-bit IV (NIST SP 800-38D)

    // "Encrypt" = sentinel prefix + base64(plaintext).
    // Stateless: decryptDataEncryptionKey reverses this without any Map lookup.
    const encryptedDEK = MOCK_PREFIX + plaintextDEK.toString("base64");

    return { encryptedDEK, plaintextDEK, iv };
  }

  async decryptDataEncryptionKey(
    encryptedDEK: string,
    _keyRingRef: string
  ): Promise<Buffer> {
    if (!encryptedDEK.startsWith(MOCK_PREFIX)) {
      throw new Error(
        `KMSMock: encryptedDEK does not have the expected mock prefix. ` +
        `This DEK was not generated by KMSMock (got "${encryptedDEK.slice(0, 20)}…"). ` +
        `Do not use KMSMock with real KMS-encrypted DEKs.`
      );
    }
    const b64 = encryptedDEK.slice(MOCK_PREFIX.length);
    return Buffer.from(b64, "base64");
  }

  /** Always 0 — stateless mock has no store to count. */
  get keyCount(): number {
    return 0;
  }
}
